apiVersion: v1
kind: Service
metadata:
  name: {{ include "esbk.fullname" . }}
  labels:
    {{- include "esbk.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.monitoringport }}
      targetPort: monitoring
      protocol: TCP
      name: monitoring      
  selector:
    {{- include "esbk.selectorLabels" . | nindent 4 }}
