apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksbsample
spec:
  template:
    spec:
      containers:
      - name: ksbsample
        imagePullPolicy: IfNotPresent
        env:
        - name: environment
          value: prod
