resources:
- ../base

namePrefix: prod-

configMapGenerator:
- name: ksbsample-environment
  files:
  - environment.properties
  - sample.properties

secretGenerator:
- name: ksbsample-credentials
  files:
  - credentials.properties

