apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksbsample
spec:
  selector:
    matchLabels:
      app: ksbsample
  template:
    spec:
      containers:
      - name: ksbsample
        env:
        - name: environment
          value: dev
