apiVersion: v1
kind: Service
metadata:
  name: ksbsample
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  selector:
    app: ksbsample
  ports:
  - name : http
    port: 8080
    targetPort: 8080
  - name : monitoring
    port: 8081
    targetPort: 8081

