resources:
- ../../base

namePrefix: dev-

configMapGenerator:
- name: ksbsample-environment
  files:
  - environment.properties
  - sample.properties

secretGenerator:
- name: ksbsample-credentials
  files:
  - credentials.properties

patches: 
  - target:
      group: networking.k8s.io
      version: v1
      kind: Service
      name: ksbsample-service
    path: service-patch.yaml
